# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      vite-vitest:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'vitest'
          - '@vitest/*'
      mantine:
        patterns:
          - '@mantine/*'
      docusaurus:
        patterns:
          - '@docusaurus/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      lint-format:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
