# Configuration for project se-votura, connector se-votura

# Learn more about the Teamscale IDE Configuration File Format at
# <https://docs.teamscale.com/reference/teamscale-toml/>.

version = "1.0"

root = true

[server]
url = "https://exia.informatik.uni-ulm.de/teamscale/"

[project]
id = "se-votura"
