# To Run this docker compose file, you need to set the PEPPER environment variable in your shell before running the command:
# export PEPPER='your_pepper_value' (or for a one-liner: PEPPER='your_pepper_value' docker-compose up)

services:
  postgres:
    build:
      context: ./packages/db
      dockerfile: dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - votura_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: votura
      POSTGRES_PASSWORD: votura
      POSTGRES_DB: votura
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U votura']
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:4000
    ports:
      - '8080:80'

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://votura:votura@postgres:5432/votura?schema=public
      PEPPER: ${PEPPER:?PEPPER must be set}
    depends_on:
      postgres:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - '1025:1025' # SMTP server (used by the backend)
      - '8025:8025' # Web UI (open http://localhost:8025 to view sent emails)

volumes:
  votura_postgres_data:
