server {
    listen 80;

    location = /config.js {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-store";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}