components:
  parameters:
    ballotPaperId:
      name: 'ballotPaperId'
      in: 'path'
      description: |
        The unique identifier for the ballot paper.
      required: true
      schema:
        $ref: './../globals/schemas.yaml#/components/schemas/uuid'
