import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  userGuideSidebar: [{ type: 'autogenerated', dirName: 'userGuide' }],
  devGuideSidebar: [{ type: 'autogenerated', dirName: 'devGuide' }],
};

export default sidebars;
