import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apisidebar from './docs/api/sidebar';

const SIDEBARS: SidebarsConfig = {
  userGuideSidebar: [{ type: 'autogenerated', dirName: 'userGuide' }],
  devGuideSidebar: [{ type: 'autogenerated', dirName: 'devGuide' }],
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
  apiSidebar: apisidebar,
};

export default SIDEBARS;
