services:
  postgres:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - votura_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: votura
      POSTGRES_PASSWORD: votura
      POSTGRES_DB: votura

volumes:
  votura_postgres_data: