components:
  parameters:
    candidateId:
      name: 'candidateId'
      in: 'path'
      description: |
        The unique identifier for the candidate.
      required: true
      schema:
        $ref: './../globals/schemas.yaml#/components/schemas/uuid'
