components:
  parameters:
    electionId:
      name: 'electionId'
      in: 'path'
      description: |
        The unique identifier for the election.
      required: true
      schema:
        type: 'string'
        format: 'uuid'
        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        example: '123e4567-e89b-12d3-a456-426614174000'
