components:
  parameters:
    electionId:
      name: 'electionId'
      in: 'path'
      description: |
        The unique identifier for the election.
      required: true
      schema:
        $ref: './../globals/schemas.yaml#/components/schemas/uuid'
