name: 🛠️ Administrative Task
description: Describe a task that is not related to any source code.
# title: ""
labels: ["Administrative"]
projects: ["SE-UUlm/6"]
type: "Task"
# assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

        Please note that your issue may already be added! Please search on the issue tracker before creating one.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? Leave empty if should contact you via GitHub.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the task that should be solved
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you see!
      # value: ""
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions you've considered.
      placeholder: Tell us what your alternatives are!
      # value: ""
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the request here.
      # placeholder: ""
      # value: ""
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        - [ ] Add all labels that are relevant to this issue.
        - [ ] Enter a priority. 
        - [ ] If this issue is related to a requirement, add the same "REQ level" as the corresponding requirement and link the REQ-Issue as a parent to this issue, else use "NOT SET".
        - All other fields should be not filled out and will be added later by the dev team.
