name: 🐞 Bug report
description: Create a report to help us improve.
# title: ""
labels: ["Bug"]
projects: ["votura"]
# type: "Bug"
# assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please note that your bug may already be reported! Please search on the issue tracker before creating one.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? Leave empty if should contact you via GitHub.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: A clear and concise description of how to reproduce the behavior.
      placeholder: Tell us what to do to reproduce the bug!
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you want to see!
      value: "I expect..."
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Tell us what operating system you are using.
      multiple: true
      options:
        - iOS
        - Android
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Tell us what browser you are using.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Show us what you want to see!
      # value: ""
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: OS version, browser version, application version, ...
      # value: ""
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: "Log output"
      # value: ""
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        - [ ] Add all labels that are relevant to this issue.
        - [ ] Enter a priority. 
        - [ ] If this issue is related to a requirement, add the same "REQ level" as the corresponding requirement and link the REQ-Issue as a parent to this issue, else use "NOT SET".
        - All other fields should be not filled out and will be added later by the dev team.
