/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessTokenBlacklist {
  accessTokenId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
}

export interface BallotPaper {
  createdAt: Generated<Timestamp>;
  description: string | null;
  electionId: string;
  id: Generated<string>;
  maxVotes: number;
  maxVotesPerCandidate: number;
  modifiedAt: Generated<Timestamp>;
  name: string;
}

export interface BallotPaperSection {
  ballotPaperId: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  maxVotes: number;
  maxVotesPerCandidate: number;
  modifiedAt: Generated<Timestamp>;
  name: string;
}

export interface BallotPaperSectionCandidate {
  ballotPaperSectionId: string;
  candidateId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
}

export interface Candidate {
  createdAt: Generated<Timestamp>;
  description: string | null;
  electionId: string;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
  title: string;
}

export interface Election {
  allowInvalidVotes: Generated<boolean>;
  configFrozen: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  description: string | null;
  electionCreatorId: string;
  generator: Numeric | null;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
  name: string;
  primeP: Numeric | null;
  primeQ: Numeric | null;
  private: Generated<boolean>;
  privKey: Numeric | null;
  pubKey: Numeric | null;
  votingEndAt: Timestamp;
  votingStartAt: Timestamp;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerificationTokenExpiresAt: Timestamp | null;
  emailVerificationTokenHash: string | null;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
  passwordHash: string;
  passwordResetTokenExpiresAt: Timestamp | null;
  passwordResetTokenHash: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  refreshTokenHash: string | null;
  verified: Generated<boolean>;
}

export interface Voter {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
  voterGroupId: string;
}

export interface VoterGroup {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
  name: string;
  privKey: string | null;
  pubKey: string | null;
  voterTokensGenerated: Generated<boolean>;
}

export interface VoterRegister {
  ballotPaperId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  modifiedAt: Generated<Timestamp>;
  voted: Generated<boolean>;
  voterId: string;
}

export interface DB {
  accessTokenBlacklist: AccessTokenBlacklist;
  ballotPaper: BallotPaper;
  ballotPaperSection: BallotPaperSection;
  ballotPaperSectionCandidate: BallotPaperSectionCandidate;
  candidate: Candidate;
  election: Election;
  user: User;
  voter: Voter;
  voterGroup: VoterGroup;
  voterRegister: VoterRegister;
}
