const OK_CODE = 200;
const BAD_REQUEST_CODE = 400;
const NOT_FOUND_CODE = 404;
const NOT_IMPLEMENTED_CODE = 501;

export enum StatusCode {
  OK = OK_CODE,
  BAD_REQUEST = BAD_REQUEST_CODE,
  NOT_FOUND = NOT_FOUND_CODE,
  NOT_IMPLEMENTED = NOT_IMPLEMENTED_CODE,
}
