services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - votura_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: votura
      POSTGRES_PASSWORD: votura
      POSTGRES_DB: votura

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - '1025:1025' # SMTP server (used by the backend)
      - '8025:8025' # Web UI (open http://localhost:8025 to view sent emails)

volumes:
  votura_postgres_data:
