openapi: '3.1.0'
info:
  title: 'Votura backend HTTP-API definition'
  summary: 'Votura backend HTTP-API definition'
  description: |
    ---
    This is the OpenAPI specification for the communication to the votura backend via the REST-API.
    The votura fronted and backend communicate via this API.
  termsOfService: 'https://github.com/SE-UUlm/votura?tab=coc-ov-file'
  contact:
    name: 'Votura Dev-Team'
    # email: ''
    url: 'https://github.com/SE-UUlm/votura/https://github.com/SE-UUlm/votura/discussions/categories/q-a'
  license:
    name: 'MIT'
    url: 'https://github.com/SE-UUlm/votura?tab=MIT-1-ov-file'
  version: '0.0.0'
externalDocs:
  url: 'https://se-uulm.github.io/votura/'
  description: 'The votura documentation'
servers:
  - url: 'http://localhost:{port}/api/v1'
    description: 'The default local development server.'
    variables:
      port:
        default: '5000'
        description: 'The port of the local development server, the votura backend.'
  # - url: 'https://votura.informatik.uni-ulm.de/api/v1'
  #   description: 'The live bwCloud testing votura backend server'
  # - url: 'https://votura.com/api/v1'
  #   description: 'The live production votura backend server'
components:
  securitySchemes:
    voturaBackendAuth:
      type: apiKey
      in: header
      name: Authentication
      description: |
        With this API access token the user can authenticate and authorize himself against the votura backend.
tags:
  - name: 'Elections'
    description: |
      It contains all information about the election.
  - name: 'Users'
    description: |
      The user can manage there own elections.
paths:
  /elections:
    $ref: './elections/paths.yaml#/components/pathItems/elections'
  /elections/{electionId}:
    $ref: './elections/paths.yaml#/components/pathItems/specificElection'
  /elections/{electionId}/freeze:
    $ref: './elections/paths.yaml#/components/pathItems/freezeElection'
  /elections/{electionId}/unfreeze:
    $ref: './elections/paths.yaml#/components/pathItems/unfreezeElection'
  /tokens:
    $ref: './user/paths.yaml#/components/pathItems/tokens'
# TODO:
# paging & paging size for all elections
# Linting: BOLA, BFLA & BOPLA login?
# was sind links in den responses?
# documentation explanation, delete api folder, VSC extension
# turbo input folder for docs build
# Swagger Hub
