openapi: '3.1.0'
info:
  title: 'Votura API Specification'
  summary: 'TODO'
  description: 'This is the OpenAPI specification for communication to the votura backend via the REST-API.'
  termsOfService: 'https://github.com/SE-UUlm/votura?tab=coc-ov-file'
  contact:
    name: 'Votura Dev-Team'
    url: 'https://github.com/SE-UUlm/votura/https://github.com/SE-UUlm/votura/discussions/categories/q-a'
    # email: 'info@votura.com'
  license:
    name: 'MIT'
    # identifier: ''
    url: 'https://github.com/SE-UUlm/votura?tab=MIT-1-ov-file'
  version: '1.0.0'
paths:
  /elections:
    summary: 'Manage elections.'
    description: 'The endpoint for CRUD operations on elections.'
    get:
      tags:
        - election
      summary: 'Get elections'
      description: 'TODO'
      operationId: 'getElections'
      #parameters:
      responses:
        '200':
          description: 'Successful response. OK.'
          # headers:
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  type: 'object'
                  properties:
                    id:
                      type: 'integer'
                      description: 'The internal unique identifier of the election.'
                    name:
                      type: 'string'
                      description: 'The name of the election.'
          # links:
