openapi: '3.1.0'
info:
  title: 'Votura backend HTTP-API definition'
  description: |
    ---
    This is the OpenAPI specification for the communication to the votura backend via the REST-API.
    The votura fronted and backend communicate via this API.
  termsOfService: 'https://github.com/SE-UUlm/votura?tab=coc-ov-file'
  contact:
    name: 'Votura Dev-Team'
    # email: ''
    url: 'https://github.com/SE-UUlm/votura/https://github.com/SE-UUlm/votura/discussions/categories/q-a'
  license:
    name: 'MIT'
    url: 'https://github.com/SE-UUlm/votura?tab=MIT-1-ov-file'
  version: '0.0.0'
externalDocs:
  url: 'https://se-uulm.github.io/votura/'
  description: 'The votura documentation'
servers:
  - url: 'http://localhost:{port}/api/v1'
    description: 'The default local development server.'
    variables:
      port:
        default: '5000'
        description: 'The port of the local development server, the votura backend.'
  - url: 'https://votura.informatik.uni-ulm.de/api/v1'
    description: 'The live bwCloud testing votura backend server'
  # - url: 'https://votura.com/api/v1'
  #   description: 'The live production votura backend server'
components:
  securitySchemes:
    voturaBackendAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        With this JWT access token the user can authenticate and authorize himself against the votura backend.
tags:
  - name: 'Elections'
    description: |
      It contains all information about the election.
  - name: 'Users'
    description: |
      Managing user accounts and sessions.
paths:
  /elections:
    $ref: './elections/elections.yaml'
  /elections/{electionId}:
    $ref: './elections/specificElection.yaml'
  /elections/{electionId}/freeze:
    $ref: './elections/freeze.yaml'
  /elections/{electionId}/unfreeze:
    $ref: './elections/unfreeze.yaml'
  /users/user:
    $ref: './user/user.yaml'
  /users/verifyEmail:
    $ref: './user/verifyEmail.yaml'
  /users/login:
    $ref: './user/login.yaml'
  /users/refreshTokens:
    $ref: './user/refreshTokens.yaml'
  /users/requestPasswordReset:
    $ref: './user/requestPasswordReset.yaml'
  /users/resetPassword:
    $ref: './user/resetPassword.yaml'
  /users/logout:
    $ref: './user/logout.yaml'
# TODO:
# duplicate email
# duplicate password
# linting
# duplicate apiTokenObject
# was sind links in den responses?
# turbo input folder for docs build
