components:
  parameters:
    voterGroupId:
      name: 'voterGroupId'
      in: 'path'
      description: |
        The unique identifier for the voter Group.
      required: true
      schema:
        $ref: './../globals/schemas.yaml#/components/schemas/uuid'
