name: Build & deploy docs

on:
  push:

jobs:
  build-puml:
    name: Build PlantUML diagrams
    runs-on: 
      labels: ubuntu-latest
    container:
      image: ubuntu:22.04
    continue-on-error: false
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install curl
        run: 
          |
          apt-get update
          apt-get install -y curl graphviz libfreetype6 fontconfig
      - name: Download PlantUML
        run: |
          curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
      - name: Build PlantUML SVG files
        run: |
          find ./apps/docs/static/uml -name "*.puml" -exec java -jar plantuml.jar -tsvg {} \;
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/docs/static/uml 
      - run: |
          ls -la ./apps/docs/static/uml

  build:
    name: Build documentation
    needs: build-puml
    runs-on: 
      labels: ubuntu-latest
    container:
      image: ubuntu:22.04
    continue-on-error: false
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./apps/docs/package-lock.json
      - name: Download UML Artifacts
        uses: actions/download-pages-artifact@v3
        with:
          path: ./apps/docs/static/uml
      - name: Install dependencies
        run: |
          cd ./apps/docs/
          npm ci
      - name: Build website
        run: |
          cd ./apps/docs/
          npm run build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/docs/build

  deploy:
    name: Deploy documentation
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/33-setup-github-pages-docs '
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: 
      labels: ubuntu-latest
    container:
      image: ubuntu:22.04
    continue-on-error: false
    timeout-minutes: 10

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
