name: Build docs

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build documentation
    runs-on: 
      labels: linux-sp
    continue-on-error: false
    container:
      image: ubuntu:22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Change directory
        run: cd ./apps/docs/
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./apps/docs/package-lock.json
      - name: Install dependencies
        run: |
          cd ./apps/docs/
          npm ci
      - name: Test build website
        run: |
          cd ./apps/docs/
          npm run build
